---
title: "Mini-Project 2"
author: "Beth Campbell, Lola Roberts and Felicia Villalobos"
date: "March 22, 2018"
output: html_document
---

```{r}
library(tidyverse)
```


```{r, include=FALSE}
load("house_elections.rda")
load("candidates.rda")
load("committees.rda")
load("contributions.rda")
```

```{r}
library(tidyverse)
library(ggplot2)
```

```{r}
# #join comtributions and candidates (both have cand_id)
# #now will have cand name, org, transaction amount $
# #then filter out the negative transation amounts 
# 
# test1 <- contributions %>%
#   filter(transaction_amt > 0) %>%
#   select(cand_id, transaction_amt, tran_id)
#   
# test2 <- candidates %>%
#   select(cand_id, cand_name, cand_election_yr, cand_party_affiliation)
# 
# comfilter <- committees %>%
#   select(cand_id, cmte_name, cmte_type)
```

```{r}
#trying to join the above stuff 

# newthing <- test1 %>%
#   inner_join(test2, by = "cand_id")

#newerthing <- comfilter %>% 
 # filter(cand_id as NA) %>%
  #will have all contributions that went to candidate committee
  #inner_join(newthing, by = "cand_id")
```

```{r}
# what we want from candidates
candFilter <- candidates %>%
  select(cand_id, cand_name, cand_party_affiliation)

# what we want from contributions
contrFilter <- contributions %>%
  select(cmte_id, name, state, transaction_amt, cand_id)

#joining contributions and candidates
canCon <- candFilter %>%
  full_join(contrFilter, candFilter, by = "cand_id")

# organizing canCon to show what we want
# this is the new data set that has no na's in the cand_name slot 
canCon <- canCon %>%
  arrange(cand_id) %>%
  filter(!is.na(cand_name)) %>%
  group_by(cand_name)

View(canCon)
```


